name: Build and Deploy
enable-email-notifications: true

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: podman
    container: docker.io/library/node:26
    name: Build and deploy

    steps:
      - name: Install deps 🛎️
        run: |
          apt-get update
          apt-get install -y rsync

      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Deploy Vite App 🚀
        uses: https://codeberg.org/act/deploy-vite@v1
        with:
          host-user: ${{ secrets.HOST_USER }}
          host-ip: ${{ secrets.HOST_IP }}
          host-key: ${{ secrets.HOST_PRIVATE_SSH_KEY }}
          from: dist/
          to: ~/pages/wp-pager
          to-pages-branch: true
