name: Build and Deploy
enable-email-notifications: true

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: podman
    container: docker.io/library/node:26
    name: Build and deploy

    steps:
      - name: Install deps 🛎️
        run: |
          apt-get update
          apt-get install -y rsync

      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: https://github.com/JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: pages
